spring:
    config:
        import: classpath:starter.yml
---
server:
    port: 8010
spring:
    application:
        name: authservice
auth:
    url: http://localhost:8005
    realm: microservices
    client-id: ${spring.application.name}
    client-secret: ${spring.application.name}
